name: teacher_side
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separatedc by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  
  cloud_firestore: ^1.0.2
  hidden_drawer_menu: ^2.0.1
  get:
  flutter_speed_dial: ^2.1.1
  google_fonts: ^2.1.0
  firebase_core: "^1.0.2"
  firebase_messaging: ^10.0.1
  grouped_list: ^4.0.0
  photo_view: ^0.11.1
  crypto: ^3.0.0
  flutter_styled_toast: ^2.0.0
  flutter_form_bloc: ^0.20.4
  form_bloc: ^0.20.4
  rxdart:
  flutter_bounce: ^1.1.0
  flutter_filereader: ^2.2.0
  get_storage:
  permission_handler:

  provider:
  flutter_document_picker: ^4.0.1
  bloc: ^7.0.0
  uuid: ^3.0.4
  open_file: ^3.2.1  
  backendless_sdk: ^7.0.0
  intl: ^0.17.0

  flutter_file_preview:
    git:
        url: git://github.com/aliyoge/flutter_file_preview.git
  circular_bottom_navigation: ^1.0.1
  sizer: ^1.1.8
  animations: ^2.0.0
  load: ^1.0.0
  file_picker: ^3.0.0
  carousel_slider: ^3.0.0
  rflutter_alert: ^2.0.2
  flutter_local_notifications: ^6.0.0
  ripple_effect: ^0.1.1
  circular_clip_route: ^0.2.0
  motion_widget: ^1.0.2
  flutter_show_more: ^0.1.2
  http: ^0.13.3
  font_awesome_flutter: ^8.11.0
  loading_indicator: ^2.1.1
  flutter_downloader: ^1.5.2
  fluttertoast: ^7.1.8
  flutter_swipe_action_cell: ^2.0.0
  image_picker:
  sqflite: ^2.0.0+3
  flutter_pdfview: ^1.1.0
  flutter_staggered_animations: "^0.1.2"
  webview_flutter: ^2.0.2
dev_dependencies:
  flutter_native_splash: 
    
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 
flutter_icons:
  android: "launcher_icon" 
  ios: false
  image_path: "assets/images/karari.png"  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_native_splash:
  image: assets/images/karari.png
  color: "ffffff"
  fullscreen: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Jetbrains Mono
      fonts:
        - asset: assets/fonts/jetbrains/jetBrainsMono-Bold.ttf
        - asset: assets/fonts/jetbrains/jetBrainsMono-BoldItalic.ttf
        - asset: assets/fonts/jetbrains/jetBrainsMono-Italic.ttf
        - asset: assets/fonts/jetbrains/jetBrainsMono-Medium.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
